import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CloudSun,Shirt,Plus,CloudRain,Wind,Sun,MapPin,Heart,UserRound,Camera,Search,Trash2,Sparkles,ChevronRight,RefreshCw,Upload,Check} from 'lucide-react';
import './styles.css';

const CATS=[['all','Tout'],['jupe','Jupes'],['pantalon','Pantalons'],['robe','Robes'],['haut','Hauts'],['manteau','Manteaux'],['chaussures','Chaussures'],['boucles','Boucles'],['collier','Colliers'],['bracelet','Bracelets'],['sac','Sacs']];
const DEMO=[
 {id:'d1',name:'Robe rouge',cat:'robe',color:'Rouge',season:'été',img:'/assets/modele-1.jpg'},
 {id:'d2',name:'Jupe crayon bordeaux',cat:'jupe',color:'Bordeaux',season:'toute saison',img:'/assets/inspiration-poses.png'},
 {id:'d3',name:'Look glamour',cat:'robe',color:'Rouge',season:'soirée',img:'/assets/modele-2.jpg'}
];
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function App(){
 const [tab,setTab]=useState('home'); const [cat,setCat]=useState('all'); const [items,setItems]=useState(()=>load('fm_items',DEMO)); const [weather,setWeather]=useState(null); const [city,setCity]=useState('Paris'); const [loadingWeather,setLoadingWeather]=useState(false); const [query,setQuery]=useState(''); const [style,setStyle]=useState('Chic'); const [toast,setToast]=useState(''); const fileRef=useRef();
 useEffect(()=>localStorage.setItem('fm_items',JSON.stringify(items)),[items]);
 useEffect(()=>{getWeather()},[]);
 function notify(s){setToast(s);setTimeout(()=>setToast(''),2200)}
 async function getWeather(){setLoadingWeather(true); try{let lat=48.8566,lon=2.3522,name='Paris'; if(navigator.geolocation){await new Promise(res=>navigator.geolocation.getCurrentPosition(p=>{lat=p.coords.latitude;lon=p.coords.longitude;res()},()=>res(),{timeout:3000}))}; const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`); const d=await r.json(); setWeather({temp:Math.round(d.current.temperature_2m),feels:Math.round(d.current.apparent_temperature),wind:Math.round(d.current.wind_speed_10m),rain:d.daily.precipitation_probability_max?.[0]??0,code:d.current.weather_code}); setCity(name)}catch(e){setWeather({temp:18,feels:18,wind:15,rain:0,code:0});setCity('Paris')}finally{setLoadingWeather(false)}}
 const filtered=useMemo(()=>items.filter(x=>(cat==='all'||x.cat===cat)&&x.name.toLowerCase().includes(query.toLowerCase())),[items,cat,query]);
 const rec=useMemo(()=>recommend(items,weather,style),[items,weather,style]);
 function addFile(e){const f=e.target.files?.[0]; if(!f)return; const url=URL.createObjectURL(f); const name=f.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' '); const guessed=guessCat(name); const it={id:crypto.randomUUID(),name:name||'Nouveau vêtement',cat:guessed,color:'À définir',season:'toute saison',img:url}; setItems(v=>[it,...v]); setCat(guessed); setTab('wardrobe'); notify(`Ajouté dans « ${label(guessed)} »`); e.target.value=''}
 function remove(id){setItems(v=>v.filter(x=>x.id!==id));notify('Article supprimé')}
 return <div className="app">
  <header className="top"><div><div className="brand">Fassions Mode</div><div className="tag">Ton style, en harmonie avec la météo</div></div><button className="avatar"><img src="/assets/modele-1.jpg"/></button></header>
  <main>
   {tab==='home'&&<Home weather={weather} city={city} loading={loadingWeather} refresh={getWeather} rec={rec} setTab={setTab} style={style} setStyle={setStyle}/>} 
   {tab==='wardrobe'&&<Wardrobe items={filtered} cat={cat} setCat={setCat} query={query} setQuery={setQuery} remove={remove} openUpload={()=>fileRef.current?.click()}/>} 
   {tab==='looks'&&<Looks rec={rec} style={style} setStyle={setStyle} weather={weather}/>} 
   {tab==='weather'&&<Weather weather={weather} city={city} refresh={getWeather} rec={rec}/>} 
   {tab==='profile'&&<Profile items={items}/>} 
  </main>
  <input ref={fileRef} hidden type="file" accept="image/*" onChange={addFile}/>
  <nav className="nav">{[['home','Accueil',CloudSun],['wardrobe','Garde-robe',Shirt],['looks','Tenues',Sparkles],['weather','Météo',Sun],['profile','Profil',UserRound]].map(([id,t,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={20}/><span>{t}</span></button>)}</nav>
  {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
 </div>
}
function Home({weather,city,loading,refresh,rec,setTab,style,setStyle}){return <section className="page"><div className="hero"><div><div className="location"><MapPin size={15}/>{city}</div><h1>Ma tenue du jour</h1><p>Une proposition créée avec ta garde-robe et la météo.</p></div><button className="iconBtn" onClick={refresh}><RefreshCw size={18}/></button></div><WeatherCard weather={weather} loading={loading}/><div className="sectionHead"><h2>Look recommandé</h2><button onClick={()=>setTab('looks')}>Voir tout <ChevronRight size={16}/></button></div><LookCard rec={rec}/><div className="chips">{['Chic','Élégante','Décontractée','Soirée'].map(s=><button className={style===s?'chip active':''||'chip'} onClick={()=>setStyle(s)} key={s}>{s}</button>)}</div><button className="primary wide" onClick={()=>setTab('wardrobe')}><Plus size={18}/> Ajouter un vêtement</button></section>}
function WeatherCard({weather,loading}){if(loading||!weather)return <div className="weather card"><div className="skeleton"/></div>; return <div className="weather card"><div className="weatherMain"><Sun size={48}/><div><b>{weather.temp}°C</b><span>Ressenti {weather.feels}°C</span></div></div><div className="weatherStats"><span><CloudRain size={17}/>{weather.rain}% pluie</span><span><Wind size={17}/>{weather.wind} km/h</span><span><Sun size={17}/>UV adapté</span></div></div>}
function LookCard({rec}){return <div className="look card"><div className="model"><img src={rec.model}/></div><div className="pieces">{rec.pieces.map((p,i)=><div className="piece" key={i}><img src={p.img}/><div><b>{p.name}</b><small>{label(p.cat)}</small></div></div>)}</div></div>}
function Wardrobe({items,cat,setCat,query,setQuery,remove,openUpload}){return <section className="page"><div className="hero"><div><h1>Ma garde-robe</h1><p>Ajoute tes pièces et elles seront réutilisées dans tes looks.</p></div><button className="primary" onClick={openUpload}><Camera size={17}/> Ajouter</button></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un vêtement..."/></div><div className="categoryGrid">{CATS.slice(0,7).map(([id,t])=><button className={cat===id?'cat active':'cat'} onClick={()=>setCat(id)} key={id}><span>{iconFor(id)}</span>{t}</button>)}</div><div className="filters">{CATS.slice(7).map(([id,t])=><button className={cat===id?'chip active':'chip'} onClick={()=>setCat(id)} key={id}>{t}</button>)}</div><div className="grid">{items.map(x=><div className="item card" key={x.id}><div className="itemImg"><img src={x.img}/><button onClick={()=>remove(x.id)} className="delete"><Trash2 size={15}/></button></div><b>{x.name}</b><small>{label(x.cat)} · {x.color}</small></div>)}</div>{!items.length&&<div className="empty">Aucun vêtement dans cette catégorie.</div>}</section>}
function Looks({rec,style,setStyle,weather}){return <section className="page"><h1>Créer une tenue</h1><p>Choisis une ambiance, Fassions Mode compose le reste.</p><div className="chips">{['Chic','Élégante','Décontractée','Soirée','Travail','Romantique'].map(s=><button className={style===s?'chip active':'chip'} onClick={()=>setStyle(s)} key={s}>{s}</button>)}</div><h2>Selon la météo</h2><LookCard rec={rec}/><div className="moods"><div>☀️ <b>Glamour</b><small>Rouge & noir</small></div><div>✨ <b>Sophistiquée</b><small>Neutres satinés</small></div><div>🖤 <b>Chic</b><small>Pièces structurées</small></div><div>🌸 <b>Féminine</b><small>Douce & élégante</small></div><div>🔥 <b>Audacieuse</b><small>Contrastes forts</small></div></div></section>}
function Weather({weather,city,refresh,rec}){return <section className="page"><div className="hero"><div><div className="location"><MapPin size={15}/>{city}</div><h1>Météo</h1></div><button className="iconBtn" onClick={refresh}><RefreshCw size={18}/></button></div><WeatherCard weather={weather} loading={!weather}/><h2>Tenue adaptée aujourd'hui</h2><LookCard rec={rec}/><div className="tips card"><b>Conseils de style</b><p>{weather?.rain>40?'Privilégie une matière qui supporte l’humidité et ajoute un manteau léger.':weather?.temp<10?'Opte pour des couches chaudes, un manteau et des chaussures fermées.':weather?.temp>24?'Privilégie les matières légères et respirantes.':'Une tenue intermédiaire et des accessoires faciles à retirer seront adaptés.'}</p></div></section>}
function Profile({items}){return <section className="page"><div className="profile card"><img src="/assets/modele-1.jpg"/><h1>Mon profil</h1><p>Ta garde-robe contient <b>{items.length}</b> pièces.</p><div className="profileRow"><span>Style préféré</span><b>Chic & féminin</b></div><div className="profileRow"><span>Couleurs</span><b>Bordeaux · Noir · Beige</b></div><div className="profileRow"><span>Ville météo</span><b>Paris</b></div></div><div className="tips card"><b>Ton mannequin</b><p>Les visuels de l'application utilisent ton modèle de référence. Les photos de ta garde-robe restent dans ton navigateur dans cette version.</p></div></section>}
function recommend(items,w,style){const t=w?.temp??18; let eligible=items.filter(x=>x.cat!=='all'); const preferred=t<10?['manteau','pantalon','haut','chaussures']:t<18?['manteau','haut','jupe','pantalon','chaussures']:t>24?['robe','jupe','haut','chaussures']:['jupe','robe','haut','chaussures']; let pieces=[]; preferred.forEach(c=>{const p=eligible.find(x=>x.cat===c);if(p&&!pieces.some(q=>q.cat===c))pieces.push(p)}); if(!pieces.length)pieces=eligible.slice(0,4); const model=pieces.find(x=>x.img)?.img||'/assets/modele-1.jpg'; return {pieces:pieces.slice(0,5),model,style};}
function guessCat(s){s=s.toLowerCase(); if(s.includes('jupe'))return'jupe';if(s.includes('robe'))return'robe';if(s.includes('pantalon'))return'pantalon';if(s.includes('manteau')||s.includes('veste'))return'manteau';if(s.includes('chauss'))return'chaussures';if(s.includes('collier'))return'collier';if(s.includes('boucle'))return'boucles';if(s.includes('bracelet'))return'bracelet';if(s.includes('sac'))return'sac';return'haut'}
function label(c){return CATS.find(x=>x[0]===c)?.[1]||'Vêtement'}
function iconFor(id){return ({jupe:'👗',pantalon:'👖',robe:'👗',haut:'👚',manteau:'🧥',chaussures:'👠'})[id]||'✨'}
createRoot(document.getElementById('root')).render(<App/>);
